services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://fatemehjafari020:iamparisa@backend.jckf0ya.mongodb.net/?retryWrites=true&w=majority&appName=backend
